package org.slizaa.scanner.api.model;


/**
 * {@link INode} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractINodeAssert} instead.
 */
public class INodeAssert extends AbstractINodeAssert<INodeAssert, INode> {

  /**
   * Creates a new <code>{@link INodeAssert}</code> to make assertions on actual INode.
   * @param actual the INode we want to make assertions on.
   */
  public INodeAssert(INode actual) {
    super(actual, INodeAssert.class);
  }

  /**
   * An entry point for INodeAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myINode)</code> and get specific assertion with code completion.
   * @param actual the INode we want to make assertions on.
   * @return a new <code>{@link INodeAssert}</code>
   */
  public static INodeAssert assertThat(INode actual) {
    return new INodeAssert(actual);
  }
}
